### ISSUE TITLE
`2.0` Milestone 🚩

### ISSUE THREAD

**Issue by lluia** [zopaUK/react-components#53]
## Roadmap &nbsp; 🗺

Summarising progress of our `2.0` milestone here 💅🏻

### Rebrand 
- [ ] #51 **New typography** 
  - [ ] documentation on how to apply them
- [ ] #52 **New colors**
  - [ ] documentation on how to apply them

### Cleanup
- [ ] #49 **Rename to `<Label />`**
- [ ] #30 **Remove social media icons**
- [ ] #20 **Better naming for icons**
- [ ] #21 **Remove `<Card type="button" />**
- [ ] #17 **Standardise `<Spinner />`**
  - [ ] catch-up with design team about it
